name: Slack notification

on:
  push:
    tags:
      - 'v1*'

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Notify new release on Slack
        uses: italia/slack-notify-release-action@v0.4.0
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL }}
          project_name: Design Angular Kit
